# Generated by Django 5.2.3 on 2025-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="../media/", verbose_name="Фотография"
            ),
        ),
    ]
