# Generated by Django 5.2.4 on 2025-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplySwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('adres_board', models.IntegerField(help_text='0x40', verbose_name='Адресс платы')),
                ('adres_registr', models.IntegerField(help_text='0x20', verbose_name='Адресс регистра')),
                ('location', models.CharField(help_text='Где находится', null=True, verbose_name='Группа устройств')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Иконка')),
                ('connected', models.BooleanField(default=True, help_text='Подключено ли?', verbose_name='Подключено')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
                'ordering': ['name'],
            },
        ),
    ]