# Generated by Django 5.2.16 on 2026-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupplySwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("коридор", "switch коридор"),
                            ("Макс", "switch Макс"),
                            ("кухня", "switch кухня"),
                            ("остальные", "switch остальные"),
                        ],
                        default="коридор",
                        help_text="Где находится",
                        null=True,
                        verbose_name="Группа устройств",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "adres_board",
                    models.IntegerField(help_text="40", verbose_name="Адресс платы"),
                ),
                (
                    "adres_registr",
                    models.IntegerField(help_text="20", verbose_name="Адресс регистра"),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="media", verbose_name="Иконка"
                    ),
                ),
                (
                    "on_off",
                    models.IntegerField(
                        default=0, help_text="on_off", verbose_name="Статус"
                    ),
                ),
                (
                    "connected",
                    models.BooleanField(
                        default=True,
                        help_text="Подключено ли?",
                        verbose_name="Подключено",
                    ),
                ),
            ],
            options={
                "verbose_name": "устройство",
                "verbose_name_plural": "устройства",
                "ordering": ["name"],
            },
        ),
    ]
