# Generated by Django 5.2.1 on 2025-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupplySwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "adres_board",
                    models.IntegerField(
                        help_text="Цена", max_length=2, verbose_name="Адресс платы"
                    ),
                ),
                (
                    "adres_registr",
                    models.IntegerField(
                        help_text="Цена", max_length=2, verbose_name="Адресс регистра"
                    ),
                ),
            ],
            options={
                "verbose_name": "устройство",
                "verbose_name_plural": "устройства",
                "ordering": ["name"],
            },
        ),
    ]
