# Generated by Django 5.2.17 on 2026-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyswitch",
            name="on_off",
            field=models.BooleanField(default=True, verbose_name="ON_OFF"),
        ),
    ]
