# Generated by Django 5.2.1 on 2025-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyswitch",
            name="adres_board",
            field=models.IntegerField(help_text="Цена", verbose_name="Адресс платы"),
        ),
        migrations.AlterField(
            model_name="supplyswitch",
            name="adres_registr",
            field=models.IntegerField(help_text="Цена", verbose_name="Адресс регистра"),
        ),
    ]
