# Generated by Django 5.2.4 on 2025-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyswitch',
            name='adres_board',
            field=models.IntegerField(help_text='40', verbose_name='Адресс платы'),
        ),
        migrations.AlterField(
            model_name='supplyswitch',
            name='adres_registr',
            field=models.IntegerField(help_text='20', verbose_name='Адресс регистра'),
        ),
        migrations.AlterField(
            model_name='supplyswitch',
            name='location',
            field=models.CharField(choices=[('коридор', 'switch коридор'), ('Макс', 'switch Макс'), ('кухня', 'switch кухня'), ('остальные', 'switch остальные')], default='коридор', help_text='Где находится', null=True, verbose_name='Группа устройств'),
        ),
    ]