# Generated by Django 5.2.1 on 2025-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0002_alter_supplyswitch_adres_board_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyswitch",
            name="image",
            field=models.ImageField(
                null=True, upload_to="supply/media/photo", verbose_name="Фотография"
            ),
        ),
    ]
