# Generated by Django 5.2.4 on 2025-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_supplyswitch_adres_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyswitch',
            name='on_off',
            field=models.IntegerField(default=0, help_text='on_off', verbose_name='Статус'),
        ),
    ]