# Generated by Django 5.2.3 on 2025-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0003_supplyswitch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyswitch",
            name="adres_board",
            field=models.IntegerField(help_text="0x40", verbose_name="Адресс платы"),
        ),
        migrations.AlterField(
            model_name="supplyswitch",
            name="adres_registr",
            field=models.IntegerField(help_text="0x20", verbose_name="Адресс регистра"),
        ),
    ]
