# Generated by Django 5.2.3 on 2025-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_alter_supplyswitch_adres_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyswitch',
            name='connected',
            field=models.BooleanField(default=True, help_text='Подключено ли?', verbose_name='Подключено'),
        ),
        migrations.AlterField(
            model_name='supplyswitch',
            name='image',
            field=models.ImageField(null=True, upload_to='supply/media/photo', verbose_name='Иконка'),
        ),
    ]
